baseurl = "https://blog.lent.ink/"
languageCode = "en"
title = "Blog"
theme = "kiss"
copyright = "Blog by <a href='https://lent.ink'>lent.ink</a>"
#googleAnalytics = ""
# Number of posts per page
Paginate = 5
enableRobotsTXT = true

[params.features]
disqusOnDemand = false  # Load Disqus comments on click

[params.assets]
#customCSS = ["css/custom.css"]

[params.rss]

includeContent = true # Includes whole content in rss
authorName = "Sander Lentink" # Site author's full name
#authorEmail = "sv@lent.ink"

[params.info]
#adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = false # Adds OpenGraph and Twitter cards
homeTitle = "blog.lent.ink" # Title for home page, used in <title> !!
poweredby = false # Adds powered by Hugo and Kiss below Copyright section
related = true # Includes related articles

[params.opengraph.facebook]
#admins = [] # array of Facebook IDs
#appID = ""
#pageID = ""

[params.opengraph.twitter]
#page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

#twitter = "svlentink"
github = "svlentink"
#email = "sv@lent.ink"
#linkedin = "svlentink"
#gitlab = "svlentink"
#instagram = ""
#codepen = ""
#facebook = "svlentink"

[params.social.config]
#platforms = ["twitter","github","email","email","linkedin","gitlab"]

[params.matomoAnalytics]
#siteID = 1
#rootURL = "//matomo.example.com/"

[params.fathomAnalytics]
#rootURL = "//fathom.example.com/"

[taxonomies]
tag ="tags"

[blackfriday]
#hrefTargetBlank = true