
- run to start of nature area (and trail run 10xmastrail.admeus.pt):
  - 41.183062, -8.675447
  - 41.183973, -8.674694
  - 41.185433, -8.674113
  - 41.191871, -8.674847
  - 41.194341, -8.677166

- lunch walk 01:
  - 41.185998, -8.6813512
  - 41.1865859, -8.6827662
  - Jardim Basilio Teles, Matosinhos

- road trip geres vigo:
  - Matosinhos, Porto
  - Penedo das Letras, Vale de São Cosme
  - Baloiço Panorâmico de Esporões, Braga
  - Santuário de Nossa Senhora do Sameiro, Braga
  - Jardins do Santuário do Bom Jesus, Braga
  - Jardim de Santa Bárbara, Braga
  - Miradouro de São Mamede, Frades
  - Miradouro da Pedra Bela, Vilar da Veiga
  - Castelo de Lindoso
  - Barragem do Alto-Lindoso
  - Miradouro de Tibo, Gavieira
  - Marco de fronteira, Cevide
  - Castelo do Castro, Vigo, Spain
  - Playa de Samil, Vigo, Spain
  - Playa del Vao, Spain
  - Praia de Patos, Pontevedra, Spain
  - Monteferro, Panxón, Nigrán
  - Miradoiro do Cervo, Lovelhe
  - Santuário de Santa Luzia, Viano do Castelo
  - Vila do Conde Porto Fashion Outlet
  - Matosinhos, Porto

- 