
- run to start of nature area (and trail run 10xmastrail.admeus.pt):
  - 41.183062, -8.675447
  - 41.183973, -8.674694
  - 41.185433, -8.674113
  - 41.191871, -8.674847
  - 41.194341, -8.677166

- lunch walk 01:
  - 41.185998, -8.6813512
  - 41.1865859, -8.6827662
  - Jardim Basilio Teles, Matosinhos

- road trip geres vigo:
  - Matosinhos, Porto
  - Penedo das Letras, Vale de São Cosme
  - Baloiço Panorâmico de Esporões, Braga
  - Santuário de Nossa Senhora do Sameiro, Braga
  - Jardins do Santuário do Bom Jesus, Braga
  - Jardim de Santa Bárbara, Braga
  - Miradouro de São Mamede, Frades
  - Miradouro da Pedra Bela, Vilar da Veiga
  - Castelo de Lindoso
  - Barragem do Alto-Lindoso
  - Miradouro de Tibo, Gavieira
  - Marco de fronteira, Cevide
  - Castelo do Castro, Vigo, Spain
  - Playa de Samil, Vigo, Spain
  - Playa del Vao, Spain
  - Praia de Patos, Pontevedra, Spain
  - Monteferro, Panxón, Nigrán
  - Miradoiro do Cervo, Lovelhe
  - Santuário de Santa Luzia, Viano do Castelo
  - Vila do Conde Porto Fashion Outlet
  - Matosinhos, Porto


- walk from Campanha part1:
  - Campanha 4300-173 Porto
  - Igreja Paroquial do Bonfim
  - Lidl 4300-095, Porto
  - O Porto dos gatos
  - Jardim Marques de Oliveira
  - cafe santiago, 4000-382 Porto
  - Igreja Paroquial de Santo Ildefonso
  - Paço Episcopal do Porto
  - Ponte Luís I
  - Jardim do Morro
  - Miradouro da Serra do Pilar
  - Museu do Rosé, 4400-088
  - Caves Ferreira, 4400-082
  - Sandeman, 4400-222
  - Cais da Ribeira de Gaia
  - Cais da Ribeira
  - Praça da Ribeira
  - Jardim do Infante Dom Henrique
  - Mercado Ferreira Borges
  - R. das Flores, Porto
  - São Bento Train station
  - Praça da Liberdade 126, 4000-322 Porto
  - Monumento a Almeida Garrett
  - Francesinhas Al Forno da Baixa
  - Hard Rock Cafe, Porto
- walk from Campanha 2/2:
  - Hard Rock Cafe, Porto
  - Igreja e Torre dos Clérigos
  - Livraria Lello
  - Igreja do Carmo
  - Jardim da Cordoaria
  - SPAR VIRTUDES, Porto
  - Passeio das Virtudes, Porto
  - Jardins do Palácio de Cristal
  - Miradouro da Ponte da Arrábida
  - Jardim Botânico do Porto
  - mercado bolhao

- half marathon north:
  - Praceta António Carneiro, Matosinhos
  - Galp, Estr. da Circunvalação, 4450-000 Matosinhos
  - Zona Desportiva ao Ar Livre do Parque da Cidade
  - Bebedouro de Água, Porto
  - Castelo do Queijo
  - R. Heróis de França 133, matosinhos
  - Foz da Ribeira da Guarda, Perafita
  - R. Chouso 765, Santa Cruz do Bpo.
  - Ponte do Carro (nova), Guifões
  - O nossa Cantinho, R. Monte da Terra 344, 4450-051 Guifões
  - 41.186061, -8.674164

- 30k along the coast:
  - Metro Povoa da Varzim
  - Praia de Leça da Palmeira
  - R. Heróis de França 133, matosinhos
  - Castelo do Queijo
  - Bebedouro de Água, Porto
  - Galp, Estr. da Circunvalação, 4450-000 Matosinhos
  - Praceta António Carneiro, Matosinhos

- 27k along the coast:
  - Metro Varziela
  - Praia de Leça da Palmeira
  - R. Heróis de França 133, matosinhos
  - Castelo do Queijo
  - Bebedouro de Água, Porto
  - Galp, Estr. da Circunvalação, 4450-000 Matosinhos
  - Praceta António Carneiro, Matosinhos

- marathon along the coast:
  - Metro Modivas Centro
  - R. da Fonte, Mindelo
  - Igreja de Nossa Senhora dos Anjos, Azurara
  - Praia de Leça da Palmeira
  - R. Heróis de França 133, matosinhos
  - Castelo do Queijo
  - Forte de São João Baptista da Foz
  - Jardim do Calem
  - Castelo do Queijo
  - Bebedouro de Água, Porto
  - Galp, Estr. da Circunvalação, 4450-000 Matosinhos
  - Praceta António Carneiro, Matosinhos

