version: '2'
services:
  ssl:
    image: svlentink/letsencrypt
    volumes:
      - /tmp:/challenge
      - ~/sslcerts:/pemfiles
    environment:
      EMAIL: ssl@lent.ink
    command: lent.ink dev.lent.ink cdn.lent.ink lisanne.lent.ink

